<div class="controller-output"><?php echo $this->getContent(); ?></div>
<div class="container_btn">
    <div class="page-header">
        <h1>PhalconPress</h1>
    </div>
    <?php 
    
    if (session_status() === PHP_SESSION_ACTIVE) {  ?>
    <div><?php echo $this->tag->linkTo(['session/quit', 'Log Out', 'class' => 'btn btn-primary']); ?></div>
    <?php
    } else {?>
    <div><?php echo $this->tag->linkTo(['signup', 'Sign Up', 'class' => 'btn btn-primary']); ?></div>
    <div><?php echo $this->tag->linkTo(['session', 'Log In', 'class' => 'btn btn-primary']); ?></div>
    <?php
    } ?>
</div>

<?php

    if ($users->count() > 0) {
        ?>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($users as $user) { ?>
        <tr>
            <td><?php echo $user->id; ?></td>
            <td><?php echo $user->name; ?></td>
            <td><?php echo $user->email; ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php
    } ?>
<div class="container_btn">
    <div><?php echo $this->tag->linkTo(['post', 'Show my Posts', 'class' => 'btn btn-primary']); ?></div>
    <div><?php echo $this->tag->linkTo(['category', 'Show Category', 'class' => 'btn btn-primary']); ?></div>
</div>