<div class="controller-output"><?php echo $this->getContent(); ?></div>
<div class="container_btn">
    <div class="page-header">
        <h1>PhalconPress</h1>
    </div>
    <?php 
    if (session_status() === PHP_SESSION_ACTIVE) {  ?>
    <div><?php echo $this->tag->linkTo(['session/quit', 'Log Out', 'class' => 'btn btn-primary']); ?></div>
    <?php
    } else {?>
    <div><?php echo $this->tag->linkTo(['signup', 'Sign Up', 'class' => 'btn btn-primary']); ?></div>
    <div><?php echo $this->tag->linkTo(['session', 'Log In', 'class' => 'btn btn-primary']); ?></div>
    <?php
    } ?>
</div>
<?php
if ($posts->count() > 0) {
    ?>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Titolo</th>
            <th>Testo</th>
            <th>Action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="3">Post quantity: <?php echo $posts->count(); ?></td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($posts as $post) { ?>
        <tr>
            <td><?php echo $post->post_id; ?></td>
            <td><?php echo $post->title; ?></td>
            <td><?php echo $post->body; ?></td>
            <td><?php echo $this->tag->linkTo(['post/delete/'. $post->post_id, 'Delete Post', 'class' => 'btn btn-primary']); ?>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php
}?>
<div class="container_btn">
    <div><?php echo $this->tag->linkTo(['post/new', 'New Post', 'class' => 'btn btn-primary']); ?></div>
    <div><?php echo $this->tag->linkTo(['/', 'Go Home', 'class' => 'btn btn-primary']); ?></div>
</div>